// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: proto/kake.proto

package proto

import (
	context "context"
	reflect "reflect"
	sync "sync"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kake_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kake_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_proto_kake_proto_rawDescGZIP(), []int{0}
}

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kake_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kake_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_kake_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_kake_proto protoreflect.FileDescriptor

var file_proto_kake_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x61, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6b, 0x61, 0x6b, 0x65, 0x22, 0x06, 0x0a, 0x04, 0x56, 0x6f, 0x69, 0x64,
	0x22, 0x19, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x37, 0x0a, 0x0b, 0x4b,
	0x61, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x73, 0x12, 0x0a, 0x2e, 0x6b, 0x61, 0x6b, 0x65, 0x2e, 0x56,
	0x6f, 0x69, 0x64, 0x1a, 0x0b, 0x2e, 0x6b, 0x61, 0x6b, 0x65, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x22, 0x00, 0x30, 0x01, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_kake_proto_rawDescOnce sync.Once
	file_proto_kake_proto_rawDescData = file_proto_kake_proto_rawDesc
)

func file_proto_kake_proto_rawDescGZIP() []byte {
	file_proto_kake_proto_rawDescOnce.Do(func() {
		file_proto_kake_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_kake_proto_rawDescData)
	})
	return file_proto_kake_proto_rawDescData
}

var file_proto_kake_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_kake_proto_goTypes = []interface{}{
	(*Void)(nil),  // 0: kake.Void
	(*Hello)(nil), // 1: kake.Hello
}
var file_proto_kake_proto_depIdxs = []int32{
	0, // 0: kake.KakeService.GetHellos:input_type -> kake.Void
	1, // 1: kake.KakeService.GetHellos:output_type -> kake.Hello
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_kake_proto_init() }
func file_proto_kake_proto_init() {
	if File_proto_kake_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_kake_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kake_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_kake_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kake_proto_goTypes,
		DependencyIndexes: file_proto_kake_proto_depIdxs,
		MessageInfos:      file_proto_kake_proto_msgTypes,
	}.Build()
	File_proto_kake_proto = out.File
	file_proto_kake_proto_rawDesc = nil
	file_proto_kake_proto_goTypes = nil
	file_proto_kake_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KakeServiceClient is the client API for KakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KakeServiceClient interface {
	GetHellos(ctx context.Context, in *Void, opts ...grpc.CallOption) (KakeService_GetHellosClient, error)
}

type kakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKakeServiceClient(cc grpc.ClientConnInterface) KakeServiceClient {
	return &kakeServiceClient{cc}
}

func (c *kakeServiceClient) GetHellos(ctx context.Context, in *Void, opts ...grpc.CallOption) (KakeService_GetHellosClient, error) {
	stream, err := c.cc.NewStream(ctx, &_KakeService_serviceDesc.Streams[0], "/kake.KakeService/GetHellos", opts...)
	if err != nil {
		return nil, err
	}
	x := &kakeServiceGetHellosClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KakeService_GetHellosClient interface {
	Recv() (*Hello, error)
	grpc.ClientStream
}

type kakeServiceGetHellosClient struct {
	grpc.ClientStream
}

func (x *kakeServiceGetHellosClient) Recv() (*Hello, error) {
	m := new(Hello)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KakeServiceServer is the server API for KakeService service.
type KakeServiceServer interface {
	GetHellos(*Void, KakeService_GetHellosServer) error
}

// UnimplementedKakeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKakeServiceServer struct {
}

func (*UnimplementedKakeServiceServer) GetHellos(*Void, KakeService_GetHellosServer) error {
	return status.Errorf(codes.Unimplemented, "method GetHellos not implemented")
}

func RegisterKakeServiceServer(s *grpc.Server, srv KakeServiceServer) {
	s.RegisterService(&_KakeService_serviceDesc, srv)
}

func _KakeService_GetHellos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Void)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KakeServiceServer).GetHellos(m, &kakeServiceGetHellosServer{stream})
}

type KakeService_GetHellosServer interface {
	Send(*Hello) error
	grpc.ServerStream
}

type kakeServiceGetHellosServer struct {
	grpc.ServerStream
}

func (x *kakeServiceGetHellosServer) Send(m *Hello) error {
	return x.ServerStream.SendMsg(m)
}

var _KakeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kake.KakeService",
	HandlerType: (*KakeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetHellos",
			Handler:       _KakeService_GetHellos_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/kake.proto",
}
